import { useEffect, useState } from 'react';
import { motion, useScroll, useSpring } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Bot, BrainCircuit, Check, Download, ExternalLink, Github, Linkedin, Mail, MapPin, Send, Sparkles } from '../components/Icons';
import Navbar from '../components/Navbar'; import Cursor from '../components/Cursor'; import OrbitalScene from '../three/OrbitalScene';
import { profile, projects, skills, milestones } from '../data/portfolio';
import '../skills.css';
const Reveal=({children,className=''})=><motion.div className={className} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65}}>{children}</motion.div>;
function SectionHead({kicker,title,copy}){return <Reveal className="section-head"><p className="eyebrow">// {kicker}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</Reveal>}
export default function App(){const [loaded,setLoaded]=useState(false);const [sent,setSent]=useState(false);const {scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:90,damping:25});useEffect(()=>{const t=setTimeout(()=>setLoaded(true),1050);return()=>clearTimeout(t)},[]);return <><motion.div className="progress" style={{scaleX:progress}}/><Cursor/>{!loaded&&<div className="loader"><div className="loader-core"/><span>INITIALIZING PORTFOLIO</span></div>}<Navbar/><main>
<section id="home" className="hero"><div className="hero-grid"/><div className="hero-copy"><motion.p initial={{opacity:0}} animate={{opacity:loaded?1:0}} className="availability"><i/> AVAILABLE FOR COLLABORATION</motion.p><h1>Building the web’s<br/><em>next dimension.</em></h1><p>{profile.intro}</p><div className="actions"><a className="button primary" href="#projects">Explore work <ArrowDownRight/></a><a className="button ghost" href={profile.resume} download>Resume <Download/></a></div><div className="hero-meta"><span>01 / 08</span><span>SCROLL TO EXPLORE</span></div></div><div className="scene hero-scene"><OrbitalScene/></div><div className="orbital-label top">MERN / FULL STACK</div><div className="orbital-label bottom">GEN AI / RAG</div></section>
<section id="about" className="split about"><SectionHead kicker="Identity" title="More than the stack."/><Reveal className="about-body"><div className="identity-panel"><div className="identity-top"><div className="avatar">PJ</div><div><b>Priyanshu Joshi</b><small>Developer signal: active</small></div><span className="signal"/></div><div className="identity-lines"><p><MapPin size={15}/>{profile.location}</p><p><Sparkles size={15}/>{profile.focus}</p></div><div className="stat-row"><b>03<small>Shipped projects</small></b><b>MERN<small>Core universe</small></b><b>2027<small>B.Tech expected</small></b></div></div><p className="lead">I’m a CS undergraduate who enjoys taking an idea from a clear interface to a reliable API and data model. My current edge is full-stack JavaScript; my next frontier is making AI useful inside real products.</p></Reveal></section>
<section id="skills" className="skills-section"><SectionHead kicker="Tech orbit" title="Tools in active rotation." copy="Hover or tap a signal to see where it fits into the build."/><div className="skill-orbit"><div className="orbit-core">BUILD<small>•</small>LEARN</div>{skills.map(([name,desc],i)=><motion.button title={desc} className="skill-node" style={{'--a':`${i*30}deg`,'--d':`${150+(i%3)*30}px`}} whileHover={{scale:1.13,zIndex:5}} key={name}><span>{name}</span><i>{desc}</i></motion.button>)}</div></section>
<section id="projects" className="projects"><SectionHead kicker="Selected transmissions" title="Things I’ve brought to life."/><div className="project-list">{projects.map((p,i)=><Reveal key={p.id} className={'project '+p.accent}><div className="project-no">{p.id}</div><div className="project-main"><p className="eyebrow">{p.kind}</p><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div></div><div className="project-features">{p.features.map(f=><span key={f}><Check size={14}/>{f}</span>)}</div><a href={profile.github} target="_blank" rel="noreferrer" className="round-link" aria-label={'View '+p.title+' on GitHub'}><ArrowUpRight/></a></Reveal>)}</div></section>
<section id="ai" className="ai-section"><div className="ai-copy"><SectionHead kicker="Learning frontier" title="AI that earns its place." copy="I’m deliberately learning how to put language models to work - not just in demos, but in products people can use."/><div className="ai-pills">{['LLM integrations','Prompt engineering','RAG workflows','AI agents','Vector search'].map(x=><button key={x}><BrainCircuit size={16}/>{x}</button>)}</div></div><div className="scene ai-scene"><OrbitalScene compact/></div><div className="ai-notice"><Bot/> <span>Current focus<br/><b>Context-aware AI products</b></span></div></section>
<section id="journey" className="journey"><SectionHead kicker="Journey log" title="Forward, by building."/><div className="timeline">{milestones.map(([when,title,copy])=><Reveal className="milestone" key={title}><span>{when}</span><i/><div><h3>{title}</h3><p>{copy}</p></div></Reveal>)}</div></section>
<section id="resume" className="resume-section"><Reveal className="resume-card"><p className="eyebrow">// Curriculum vitae</p><h2>Want the full<br/>signal?</h2><p>A compact record of my projects, skills, education and achievements.</p><div className="actions"><a className="button primary" href={profile.resume} target="_blank">View resume <ExternalLink/></a><a className="button ghost" href={profile.resume} download>Download <Download/></a></div><div className="resume-sheet"><b>PRIYANSHU<br/>JOSHI</b><span>FULL STACK / AI</span></div></Reveal></section>
<section id="contact" className="contact"><SectionHead kicker="Open channel" title="Let’s build something that matters."/><div className="contact-grid"><Reveal><p className="lead">Have an opportunity, a project, or just want to exchange ideas? My inbox is open.</p><div className="socials"><a href={'mailto:'+profile.email}><Mail/> {profile.email}</a><a href={profile.github} target="_blank" rel="noreferrer"><Github/> GitHub <ArrowUpRight/></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin/> LinkedIn <ArrowUpRight/></a></div></Reveal><Reveal><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Message<textarea required placeholder="Tell me about it..." rows="3"/></label><button className="button primary" type="submit">{sent?'Message staged - thank you!':'Send transmission'} <Send/></button></form></Reveal></div></section></main><footer><span>© {new Date().getFullYear()} PRIYANSHU JOSHI</span><span>DESIGNED FOR THE NEXT BUILD</span></footer></>}
